config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :errors
  resources :hospitals
  resources :donors
  resources :dedications
  resources :contact_forms
  
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'hospitals#index'
  
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  end

end

app/models/dedication.rb
require 'will_paginate' 

class Dedication < ActiveRecord::Base

    after_initialize do 
        if new_record?
            if self.status.nil? then self.status = true end
        end 
    end

    filterrific(
        available_filters: [:sorted_by, :search_query])
                            
    belongs_to :hospital
    belongs_to :donor
    
    scope :search_query, lambda { |query|
    # Searches the dedications table on the 'dedication' column.
    # Matches using LIKE, automatically appends '%' to each term.
    # LIKE is case INsensitive with MySQL, however it is case
    # sensitive with PostGreSQL. To make it work in both worlds,
    # we downcase everything.
    return nil  if query.blank?

    # check if query exists in any dedication
    terms = [query.to_s.downcase]
    terms = terms.map { |e|
        ('%' + e + '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conds = 3
    joins(:donor).joins(:hospital).
    where(
        terms.map { |term|
        "(LOWER(dedications.dedication) LIKE ? OR
        LOWER(donors.first_name || ' ' || donors.last_name) LIKE ? OR
        LOWER(hospitals.name) LIKE ?)"
        }.join('AND'),
        *terms.map { |e| [e] * num_or_conds }.flatten
        # Mess with the AND/OR stuff to get first name last name working.
        )
    }

    scope :sorted_by, lambda { |sort_option|
        direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
        case sort_option.to_s
        when /^dedication_/
            order("dedications.dedication #{ direction }")
        when /^donor_/
            order("donors.first_name #{ direction }").includes(:donor).includes(:hospital)
        when /^hospital_/
            order("hospitals.name #{ direction }").includes(:donor).includes(:hospital)
        else
            raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
        end
    }
    
    def self.options_for_sorted_by 
        [
            ['Dedication', 'dedication_asc'],
            ['Donor', 'donor_asc'], 
            ['Hospital', 'hospital_asc']
        ]
    end
    
    def self.tiers
        ['Platinum', 'Gold', 'Silver'] # ordered list of tiers
    end
    
    def self.visible
        Dedication.where(:status => true, :published => true)
    end
end

app/controllers/dedications_controller.rb
class DedicationsController < ApplicationController
    
    WillPaginate.per_page = 9
    
    def show
        @dedication = Dedication.find_by_id(params[:id])
        @donor_logged_in = false
        if current_user
            @donor_logged_in = current_user.donor == @dedication.donor || current_user.admin?
        end
        if @dedication.nil? or !@dedication.status and !@donor_logged_in
            @error = 'Dedication'
            render 'errors/status'
        else
            @published = @dedication.published
            @hospital = Hospital.find(@dedication.hospital_id)
        end
    end
    
    def index
        @dedications = Dedication.visible
        
        @filterrific = initialize_filterrific(
            Dedication.visible, 
            params[:filterrific], 
            select_options: {
            sorted_by: Dedication.options_for_sorted_by,
            with_country_id: Hospital.options_for_select,
            }, 
            default_filter_params: {},
        ) or return 
        @dedications = @filterrific.find.page(params[:page])
        
        respond_to do |format|
            format.html
            format.js
        end
        
    rescue ActiveRecord::RecordNotFound => e
        puts "Had to reset filterrific params: #{ e.message }"
        redirect_to(reset_filterrific_url(format: :html)) and return
    end
    
    def edit
        @dedication = Dedication.find(params[:id])
        if @dedication.published
            flash[:notice] = "You can no longer edit this dedication. Please contact the admin for any concerns."
            redirect_to dedication_path(@dedication)
        end
    end
    
    def update
        @dedication = Dedication.find(params[:id])
        @dedication.dedication = params[:dedication][:dedication]
        @dedication.status = params[:dedication][:status]
        if params[:publish]
            @dedication.published = true
            hospital = Hospital.find(@dedication.hospital_id)
            flash[:notice] = "Your dedication has been published. Go to #{hospital.name}'s page to see it on the Digital Wall of Founders!"
        end
        @dedication.save!
        redirect_to donor_path(@dedication.donor)
    end
    
    def _list
        @published_dedications = Dedications.published
    end
end

app/helpers/dedications_helper.rb
module DedicationsHelper
end

app/views/dedications/_list.html.haml
#filterrific_results    
  .well.well-small
    .pull-right{ :'data-position' => 'bottom', :'data-intro' => 'Reset the filter settings to defaults.' }
      = link_to "Reset filters", reset_filterrific_url, :class => 'btn btn-default btn-sm'
    .chardin_box{ :'data-position' => 'bottom', :'data-intro' => "will_paginate's entries info works as expected." }
      = page_entries_info dedications, :model => 'dedication'
    .chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Spinner indicates update.' }
      = render_filterrific_spinner
      
  - dedications.each do |d|
    .col-md-4
      .panel.panel-info
        .panel-heading
          %h4= link_to d.donor.first_name + " " +  d.donor.last_name, donor_path(Donor.find(d.donor_id)), :method => :get
        .panel-body
          %p= d.dedication
          %p= d.hospital.name
          .btn.btn-default.btn-round.btn-sm
            %a{:href => dedication_path(d), :method => :get}
              See Dedication
              
  .text-center
    .pagination
      = will_paginate dedications
  
















      
  





































      
  

app/views/dedications/edit.html.haml
.container
  .devise
    %h1 Edit Dedication and Consent for Digital Wall of Founders
    
    = form_tag dedication_path(@dedication), :method => :put do
    
      %h2 Dedication
      = label :dedication, :dedication, 'Write a dedication for your donation'
      = text_field :dedication, 'dedication'
    
      %h2 Digital Wall of Founders
      = label :dedication, :status, 'I want my dedication to appear on the Digital Wall of Founders'
      = check_box :dedication, 'status', {}, 'true', 'false'
    
      %p We want to keep the Digital Wall of Founders as close to ther physical counterparts in hospitals as possible, so once you "Publish" your dedication you can no longer change it without contacting the admin. 
      Until you publish your dedication it will not appear on the Digital Wall of Founders.
      %p
      = submit_tag 'Save as Draft'
      = submit_tag 'Publish', name: 'publish'

app/views/dedications/index.html.haml
.container
  .well
    = form_for_filterrific @filterrific do |f|
      .row
        .col-md-8
          .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Search by first name, last name, or email.' }
            %label Search
            = f.text_field :search_query,
                           :class => 'filterrific-periodically-observed form-control'
        .col-md-4
          .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Change the sorting.' }
            %label Sorted by
            = f.select :sorted_by,
                       @filterrific.select_options[:sorted_by],{},{ :class => 'form-control' }
  
  
  #results
    = render :partial => 'dedications/list',
             :locals => { :dedications => @dedications }

app/views/dedications/index.js.erb
<% js = escape_javascript(
  render(partial: '/dedications/list', locals: { dedications: @dedications })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/dedications/new.html.haml
// should only be accessible if (logged in?) donor has a donation without a dedication

%h1 New Dedication and Consent for Digital Wall of Founders

= form_tag dedication_path(@dedication), :method => :put do

  %h2 Dedication
  = label :dedication, :dedication, 'Write a dedication for your donation'
  = text_field :dedication, 'dedication'

  %h2 Digital Wall of Founders
  = label :dedication, :status, 'I want my dedication to appear on the Digital Wall of Founders'
  = check_box :dedication, 'status', {}, true, false

  = submit_tag 'Save'
  = submit_tag 'Publish', name: 'publish'

app/views/dedications/show.html.haml
.section.section-our-team-freebie
    .parallax.filter.filter-color-black
        .image{:style => "background-image: url(#{image_path 'wood.jpg'})"}
        .container
            .content
                .team
                    .row
                        .col-md-6.col-md-offset-3
                            .card.card-member
                                .content
                                    .avatar.avatar-danger
                                        .img-circle
                                            = image_tag "#{@dedication.tier.downcase}.png"
                                    .description
                                        %h3.title 
                                            = link_to "#{@dedication.donor.first_name} #{@dedication.donor.last_name}", donor_path(Donor.find(@dedication.donor_id))
                                        %p.small-text 
                                            = @dedication.tier
                                        %p.description 
                                            = @dedication.dedication
                                        // %p This is the Content.
                                        %p= link_to "#{@hospital.name}", hospital_path(@hospital)
                                        - if @donor_logged_in && !@published
                                            %p= link_to "Edit", edit_dedication_path(@dedication.id)
                                        %p= social_share_button_tag("A donation to #{@hospital.name} by #{@dedication.donor.first_name} #{@dedication.donor.last_name} #SankaraEyeFoundation")