config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :errors
  resources :hospitals
  resources :donors
  resources :dedications
  resources :contact_forms
  
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'hospitals#index'
  
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  end

end

app/models/hospital.rb
require 'will_paginate' 
class Hospital < ActiveRecord::Base
    has_many :dedications
    has_many :donors, :through => :dedications
    
    def self.options_for_select
        order('name').map { |e| [e.name, e.id] }
    end
    
    after_initialize do 
        if new_record? then if self.status.nil? then self.status = true end end end
            
    def published_dedications_by_tier
        dbt = Hash.new
        Dedication.tiers.each do |tier|
            dbt[tier] = Dedication.where(:hospital => self.id, :tier => tier, :status => true, :published => true)
        end
        dbt
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
    
    def index
        @hospitals = Hospital.where(:status => true)
    end
    
    
    
    def show
        @hospital = Hospital.find_by_id(params[:id])
        if @hospital.nil? or @hospital.status == false
            @error = 'Hospital'
            render 'errors/status'
        else
            @tiers = Dedication.tiers
            @hospital_published_dedications_by_tier = @hospital.published_dedications_by_tier
        end
    end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/index.html.haml
-#  This file is app/views/wall/index.html.haml
.container
  .row
    .col-lg-10.col-md-offset-1
      %h1.page-header
        Wall of Founders
        %small Sankara Eye Foundation
  // .row      
  //   .well.well-small     
  //     = form_tag "/", method: :get, class: 'form-inline' do
  //       .form-group
  //         = search_field_tag :query, params[:query],
  //           placeholder: 'Search for something',
  //           size: 80,
  //           class: 'form-control'
  //         = submit_tag 'Search', name: nil, class: 'btn btn-default'  

  - @hospitals.each do |hospital|
    .row
      .col-md-6
        %a{:href => hospital_path(hospital)}
          = image_tag "hospital" + hospital.id.to_s + ".png", class: "img-responsive img-thumbnail"
            
      .col-md-6
        %h3= "#{hospital.name}"
        %h4= "#{hospital.city}, #{hospital.state}"
        %p= "Building Status: #{hospital.building_status}"
        
        .btn.btn-primary.btn-round.btn-sm
          %a{:href => hospital_path(hospital)}
            View Project
            %span.glyphicon.glyphicon-chevron-right
    %hr/

app/views/hospitals/show.html.haml
=javascript_include_tag 'application.js'

.container
  .row
    .col-lg-12
      %h1.page-header
        #{@hospital.name}
        %small #{@hospital.city}
                
  .row
    .col-md-8
      = image_tag "sankara2.jpg", class: "img-responsive img-thumbnail"
    .col-md-4
      %h3 Project Description
      %p= @hospital.story
      %li
        Surgeries:
        = @hospital.surgeries
      %li
        Cost:
        = @hospital.cost

      %head
      %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
      :css
        #map {
          height: 150px;
          width: 100%;
        }
      %body
        %h3 Location
        Latitude: #{@hospital.lat} 
        Longitude: #{@hospital.lng}
        #map
        :javascript
          function initMap() {
            var uluru = {lat: #{@hospital.lat}, lng: #{@hospital.lng} };
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 6,
              center: uluru
            });
            var marker = new google.maps.Marker({
              position: uluru,
              map: map
            });
          }
      %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyBTUBDqxJw2PidgRgXPJg_p84LCVS026l8&callback=initMap"}

  %hr/
        
  .nav.nav-tabs.nav-justified
    - @tiers.each do |tier|
      .btn.btn-default.btn-round.btn-sm
        %a{:href => "##{tier}", :class => 'jump', :name => "#{tier}"} #{tier}
  
  %hr/
  
  - @tiers.each do |tier|
    .row
      %h2{:id => "#{tier}_header"} #{tier}
      - @hospital_published_dedications_by_tier[tier].each do |dedication|
        %div{:class => "dedication", :id => dedication.id} 
          .col-md-4
            .panel.panel-info
              .panel-heading
                %h4= link_to "#{dedication.donor.first_name} #{dedication.donor.last_name}", donor_path(Donor.find(dedication.donor))
              .panel-body
                %p= dedication.dedication
                .btn.btn-default.btn-round.btn-sm
                  // :id => "view_#{dedication.id}
                  %a{:href => dedication_path(dedication), :method => :get}
                    See Dedication
    %hr/